Dev maximiliano lopez primer entregable
wizelineacademy/baz-ios-project-c4-2023 pull request #13
Opened 2023-03-31 20:08 UTC by maxOrtz

Primer entregable del proyecto BAZ

2023-04-04 00:39 UTC, amurovsky requested changes
Muy buen trabajo @maxOrtz !!!
te deje solo algunos puntos de mejora menores, como:
- Niveles de acceso
- Documentación
- Revisar algunos tests que posiblemente no funcionen como deberian

Hice comentarios en algunos lugares que no son evaluables para este entregable, te lo dejo a tu consideración si los corriges desde ahora o hasta el siguiente entregable.

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/Extensions/EndpointExtension.swift
> +extension Endpoint: EndPointProtocol {
Creo que aquí tuvimos un malentendido con lo que te mencione de las extensiones,  para protocolos no aplica 😛. si gustas lo revisamos en mentoria, para que quede mas claro 👍

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/MovieDetail/View/MovieDetailViewController.swift
> +final class MovieDetailViewController: UIViewController {
Cuidemos no incluir código que no se utilice (en este caso, se que lo dejaste por que estas avanzando el proximo entregable, pero no esta demas mencionarlo 👍 )

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/MovieSearch/View/SearchMoviesViewController.swift
> +final class SearchMoviesViewController: UIViewController {
Mismo Caso, código sin uso, repetido o boilerplate eliminarlo 👍

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/Networking/ServiceAPI.swift
> +final class ServiceAPI: Service {
💯  Generics

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/Reusables/AlertSheetActions.swift
> +    init?(rawValue: Int) {
Podrías remplazar este constructor simplemente haciendo el enum de tipo Int 👍 
ie:
`
enum AlertSheetsActions: Int {
    case trending = 0
    case nowPlaying
    case popular
    ....
}
`

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/Reusables/MainConstants.swift
> +    private static let apiKey: String = "f6cd5c1a9e6c6b965fdcab0fa6ddd38a"
Dejar los API keys expuestos en constantes no es seguro, prueba utilizando otro tipo de solución, ie: Keychain

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/TrendingModule/DataManager/TrendingBarDataManager.swift
> +    weak var interactor: TrendingBarRemoteDataOutputProtocol?
Hay alguna razón por la cual el interactor queda como internal y no privado e inyectado atravez del constructor?

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/TrendingModule/DataManager/TrendingBarDataManager.swift
> +    weak var interactor: TrendingBarRemoteDataOutputProtocol?
Siguiendo la logica de que este dataManager no funciona sin el interactor, considero que deberias inyectarlo igual que a service 👍

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/TrendingModule/DataManager/TrendingBarDispatchDecorator.swift
> +final class TrendingBarDispatchDecorator: Service {
Seria bueno que documentaras la intención de este decorador, despues de leerlo me doy cuenta que es para asegurar que se ejecuten las llamadas por el hilo principal, pero seria mas sencillo entender el por que si esta documentado 👌

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/TrendingModule/Interactor/TrendingBarInteractor.swift
> +    weak var presenter: TrendingBarInteractorOutputProtocol?
Podria ser privado el presenter no? o lo necesitas fuera de esta clase ?

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/TrendingModule/Interactor/TrendingBarInteractor.swift
> +    var remoteData: TrendingBarRemoteDataInputProtocol?
Mismo caso de nivel de acceso

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/TrendingModule/Protocols/TrendingBarProtocols.swift
> +protocol TrendingBarRouterProtocol: AnyObject {
existe alguna razón por la cual usar `AnyObject` en lugar de un tipo concreto o nada?

2023-04-04 00:39 UTC, amurovsky commented on BAZProject/MainTabController/TrendingModule/View/TrendingViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem.init(title: "Filter", style: .done, target: self, action: #selector(self.filterBy(sender:)))
Siempre que hay que evitar poner Strings literales, dale uso a tus constantes y también seria bueno hacerlos localizables

2023-04-04 00:39 UTC, amurovsky commented on BAZProjectTests/Mocks/MovieServiceMock.swift
> +        ServiceAPI(session: session).get(endpoint, callback: callback)
No deberiamos hacer llamadas reales, justo la intención del mock seria, asegurarnos que llegamos hasta el punto de ejecutar cada metodo sin tener que hacer la llamada real

2023-04-04 00:39 UTC, amurovsky commented on BAZProjectTests/TrendingBarInteractorTests.swift
> +        let movie = MovieResult(adult: false, backdropPath: "/ovM06PdF3M8wvKb06i4sjW3xoww.jpg", id: 76600, title: "Avatar: El sentido del agua", originalLanguage: "en", originalTitle: "Avatar: The Wa
Podrias usar un archivo JSON para simplificar estos tests

2023-04-04 00:39 UTC, amurovsky commented on BAZProjectTests/TrendingBarRemoteDataTests.swift
> +
Me parece que estos tests no estan realmente probando algo, ya que aqui mismo le estas haciendo `fullfill` a la `expectation` 🤔

2023-04-04 16:46 UTC, maxOrtz commented on BAZProject/MainTabController/TrendingModule/Interactor/TrendingBarInteractor.swift
> +    weak var presenter: TrendingBarInteractorOutputProtocol?
Pues para la extensiones que uso de esa clase, si lo declaro private no puedo accesar desde las extensiones.

2023-04-04 16:46 UTC, maxOrtz commented on BAZProject/MainTabController/TrendingModule/Interactor/TrendingBarInteractor.swift
> +    var remoteData: TrendingBarRemoteDataInputProtocol?
de igual forma el remoteData  para la extensiones que uso de esa clase, si lo declaro private no puedo accesar desde las extensiones.

2023-04-04 16:57 UTC, maxOrtz commented on BAZProject/MainTabController/TrendingModule/Protocols/TrendingBarProtocols.swift
> +protocol TrendingBarRouterProtocol: AnyObject {
Normalmente uso AnyObject para que mi protocolo sea "class-bound" y poder hacer referencias débiles pero el router por el momento no tiene referencias débiles asi que puedo omitirlo. Gracias.

2023-04-04 17:15 UTC, maxOrtz commented on BAZProjectTests/TrendingBarRemoteDataTests.swift
> +
Pero el fullfill() es para hacer las peticiones asyncronas y debajo pongo el wait sino la prueba nunca pasa

2023-04-04 17:33 UTC, maxOrtz commented on BAZProject/MainTabController/TrendingModule/DataManager/TrendingBarDataManager.swift
> +    weak var interactor: TrendingBarRemoteDataOutputProtocol?
Es que ese no se inicializa al crear la clase es un parámetro de el protocolo TrendingBarRemoteDataInputProtocol

2023-04-04 19:59 UTC, maxOrtz commented on BAZProjectTests/Mocks/MovieServiceMock.swift
> +        ServiceAPI(session: session).get(endpoint, callback: callback)
Pero justo no hago una llamada real porque le estoy inyectando el sessionMock

2023-04-17 23:48 UTC, amurovsky approved these changes
Buen trabajo Max! 👍

2023-04-17 23:48 UTC, merged