Dev jmanuel garcia
wizelineacademy/baz-ios-project-c4-2023 pull request #42
Opened 2023-05-08 16:55 UTC by jcarmonamx

Tercer entregable

- Uso de UserDefaults para la persistencia de datos.
- Vista de detalle de película.
- Funcionalidad para agregar o eliminar películas favoritas (persistencia de datos).
- Listado de películas favoritas (persistencia de datos).
- Se completa documentación.
- Coverage sobre 84%.

2023-05-08 17:59 UTC, arturoDiaz93 requested changes
Excelente!! Gran trabajo! Te dejé unos cuantos comentarios sencillos de resolver. Fuera de eso, no veo más detalles. Felicidades!

2023-05-08 17:59 UTC, arturoDiaz93 commented on BAZProject/Controllers/MovieDetailViewController.swift
> +        movieVM?.loadCast { actors in
No olvides el capture list en este closure.

2023-05-08 17:59 UTC, arturoDiaz93 commented on BAZProject/Resources/Extensions/String+Extensions.swift
> +        return try? NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html, .characterEncoding:String.Encoding.utf8.rawValue], documentAttributes: nil)
Hay que dejar un espacio después del guard let.

2023-05-08 17:59 UTC, arturoDiaz93 commented on BAZProject/Resources/Extensions/UserDefaults+Extensions.swift
> +        return UserDefaults(suiteName: "mx.caffeina.bazproject")!
Hay que evitar siempre el uso de force unwrapping. Es una muy mala practica. Lo mejor es tratar de costear de manera segura la instancia de UserDefaults.

2023-05-08 17:59 UTC, arturoDiaz93 commented on BAZProject/ViewModels/MovieViewModel.swift
> +        "\( Int(((movie.vote_average ?? 0) * 10).rounded()) )% de calificación"
Quizás alguna extension de string te pueda ayudar a hacer más reutilizable esto.

2023-05-08 17:59 UTC, arturoDiaz93 commented on BAZProject/ViewModels/MovieViewModel.swift
> +        isFavorite() ? UIImage(systemName: "heart.fill") : UIImage(systemName: "heart")
Podrías crear también un enum que se encargue de guardar los iconos.
Algo así:

```
/// Enum used to store the icons used through the app.
enum Icon {
    
    static let heart: UIImage = UIImage(systemName: "heart") ?? UIImage()
    static let heartFill: UIImage = UIImage(systemName: "heart.fill") ?? UIImage()
}
```


```suggestion
        isFavorite() ? Icon.heartFill : Icon.heart
```

2023-05-08 17:59 UTC, arturoDiaz93 commented on BAZProject/ViewModels/SearchViewModel.swift
> +        "Search"
Podrías crear también un enum con static properties para guardar los textos usados en la app y así evitar el uso de magic strings. Algo similar al comentario de los Iconos.

2023-05-09 00:30 UTC, jcarmonamx commented on BAZProject/ViewModels/SearchViewModel.swift
> +        "Search"
Elimine esa extensión, ya que no use esa variable computada en el código, pero si tomare en cuenta esa observación para esos casos

2023-05-10 22:11 UTC, arturoDiaz93 approved these changes
¡Excelente trabajo! Gracias por atender mis comentarios

2023-05-11 08:01 UTC, merged