Dev manuel sanchez
wizelineacademy/baz-ios-project-c4-2023 pull request #5
Opened 2023-03-31 17:02 UTC by TheManook

2023-04-04 22:51 UTC, arturoDiaz93 requested changes
Hola! Te deje algunos comentarios que necesitan revisión. En general lo veo muy bien. Quedo pendiente a tus cambios. Te dejo la guía de estilo de swift que usa google para que pueda ayudarte en el proceso de escritura de código con buenas practicas. https://google.github.io/swift/

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProject/Network/Movie.swift
> +
Este espacio extra no se necesita.

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProject/Network/Movie.swift
> +}
Esto debería estar en su propio archivo.

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProject/Network/Movie.swift
> +struct Movie: ListMoviesProtocol{
```suggestion
struct Movie: ListMoviesProtocol {
```

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProject/TrendingMovies/TrendingViewModel.swift
> +
Este espacio extra no es necesario

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProject/TrendingMovies/TrendingViewModel.swift
> +    func getmovies(_ Completion: @escaping () -> Void) {
este `completion` va con minúscula.

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProject/TrendingMovies/TrendingViewModel.swift
> +        movieApi.getMovies {  moviearray in
```suggestion
        movieApi.getMovies { moviearray in
```

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProject/TrendingMovies/TrendingViewModel.swift
> +class TrendingViewModel: MoviesListProtocol {
Podríamos declararlo como `final`

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProject/TrendingMovies/TrendingViewModel.swift
> +}
Este protocolo debería ir en su propio archivo

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProject/TrendingMovies/TrendingViewController.swift
> +        trendingModel.getmovies {
Sería mejor declarar el capture list aquí que en el dispatch.

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProjectTests/BAZProjectTests.swift
> +        sut = (UIStoryboard(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "TrendingViewController") as! TrendingViewController)
Un guard statement sería lo mejor. Recuerda que siempre hay que evitar los force unwrapping.

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProjectTests/TrendingViewControllerMock.swift
> +
este espacio no es necesario

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProjectTests/TrendingViewModelTests.swift
> +
Este espacio no es necesario.

2023-04-04 22:51 UTC, arturoDiaz93 commented on BAZProject/TrendingMovies/TrendingViewController.swift
> +    var trendingModel: MoviesListProtocol = TrendingViewModel() // protocolo para para poder realizar Testing
Podríamos declararlo como `private let`

2023-04-04 22:57 UTC, arturoDiaz93 requested changes

2023-04-04 22:57 UTC, arturoDiaz93 commented on BAZProject/Network/MovieAPI.swift
> +    func getMovies(completion: @escaping ([ListMoviesProtocol]) -> Void) {
Hay que documentar este método.

2023-04-04 22:57 UTC, arturoDiaz93 commented on BAZProjectTests/BAZProjectTests.swift
> +class BAZProjectTests: XCTestCase {
Hay que declararla como final

2023-04-04 22:57 UTC, arturoDiaz93 commented on BAZProjectTests/TrendingViewControllerMock.swift
> +class TrendingViewModelMock: TrendingViewModel {
Hay que declararla como final

2023-04-05 00:25 UTC, TheManook commented on BAZProjectTests/BAZProjectTests.swift
> +        sut = (UIStoryboard(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "TrendingViewController") as! TrendingViewController)
Hola, en el curso comentarios que al ser pruebas no había riesgo. Seria mejor practica hacerlo con el guard?

2023-04-11 15:53 UTC, arturoDiaz93 commented on BAZProject/TrendingMovies/TrendingViewController.swift
> +        trendingModel.getmovies {
Aquí hace falta el capture list.

2023-04-11 15:57 UTC, arturoDiaz93 requested changes
Hola! Sólo falta atender un par de comentarios, quedo al pendiente.

2023-04-11 15:57 UTC, arturoDiaz93 commented on BAZProjectTests/BAZProjectTests.swift
> +        sut = (UIStoryboard(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "TrendingViewController") as! TrendingViewController)
Así es, es mejor practica hacerlo con un guard, ademas de que podrías agregar un mensaje de que el test falló por eso para que en caso de no poder instanciarlo, sepamos la razón.

2023-04-13 15:42 UTC, arturoDiaz93 approved these changes
Hola! Ya puedes darle merge a tu rama de main.

2023-04-13 16:54 UTC, merged